---
test_name: curl json check

stages:
  - name: hit the endpoint and validate+save some json
    # max_retries: 3
    check: 'curl https://edgediag.services.atlassian.com/echo -H "Foobar: 1" -H "Cookie: hello there"'
    matchers:
      - json:
          payload:
            body: {}
            headers:
              foobar:
                - "1"
        save:
          cookie: payload.headers.cookie[0]

  - name: send the cookie as a different header
    # max_retries: 3
    check: 'curl https://edgediag.services.atlassian.com/echo -H "Foobar: {{ cookie }}"'
    matchers:
      - json:
          payload:
            body: {}
            headers:
              foobar:
                - "{{ cookie }}"
---
test_name: curl regex check

stages:
  - name: hit the endpoint
    max_retries: 3
    check: 'curl https://edgediag.services.atlassian.com/echo'
    matchers:
      - regex: '"x-forwarded-for":\s*\["(?P<xff>[\d\., ]+)"]'

  - name: hit the endpoint twice
    max_retries: 3
    check: 'curl https://edgediag.services.atlassian.com/echo -H "Previous-XFF: {{ 1 }}"'
    matchers:
      - regex: '"previous-xff":\s*\["(?P<xff>[\d\., ]+)"]'

  - name: hit the endpoint thrice
    max_retries: 3
    check: 'curl https://edgediag.services.atlassian.com/echo -H "Second-Previous-XFF: {{ xff }}"'
    matchers:
      - regex: '"second-previous-xff":\s*\["[\d\., ]+"]'

---
test_name: query string test

stages:
  - name: request the echo page and save a value
    check: 'curl https://edgediag.services.atlassian.com/echo'
    matchers:
      - save:
          example: payload.headers."x-request-id"[0]

  - name: insert the request id into the query string
    check: 'curl https://edgediag.services.atlassian.com/echo?prev-id={{example}}'
    matchers:
      - json:
          payload:
            query_args:
              prev-id: "{{example}}"

---
test_name: http request test

stages:
  - name: hit the endpoint using http
    check:
      url: https:/edgediag.services.atlassian.com/echo
      method: GET
      headers:
        foo: bar
    matchers:
      - json:
          payload:
            body: {}
            headers:
              foo:
                - "bar"
